src/main/java/com/recurly/v3/requests/LineItemCreate.java

There are a few new generated changes that weren't included in the last update.

Add latest generated changes

---

src/main/java/com/recurly/v3/BaseClient.java
src/main/java/com/recurly/v3/QueryParams.java
src/test/java/com/recurly/v3/JsonSerializerTest.java

These imports don't appear to be used.

Remove unused imports

---

.travis.yml
pom.xml
scripts/test

This adds Travis to build the library and run the tests on multiple JDKs to ensure it will work across environments.

Add travis yaml file

---

src/main/java/com/recurly/v3/QueryParams.java

This fixes a bug in the `QueryParams` class.

Fix QueryParams

---

README.md

Add V2 warning

---

README.md
pom.xml
src/main/java/com/recurly/v3/BaseClient.java
src/main/java/com/recurly/v3/Pager.java
src/main/java/com/recurly/v3/QueryParams.java
src/test/java/com/recurly/v3/BaseClientTest.java
src/test/java/com/recurly/v3/HeaderInterceptorTest.java
src/test/java/com/recurly/v3/PagerTest.java
src/test/java/com/recurly/v3/fixtures/MockClient.java
src/test/java/com/recurly/v3/fixtures/MockQueryParams.java

This PR increases test coverage to an acceptable level and refactors some code for testability, as well as fixes some bugs found while writing the tests. Coverage was at 49%, now it's at about 88%. The code that is not covered in BaseClient is print statements, and if Jacoco ever allows us to exclude just certain methods or lines from coverage, we'll be able to increase that. Otherwise, when we switch out to a proper logging framework we should be able to test it more easily.

Test coverage

---

LICENSE.txt
pom.xml
src/main/java/com/recurly/v3/http/HeaderInterceptor.java
src/main/resources/version.properties
src/test/java/com/recurly/v3/HeaderInterceptorTest.java

* Set version to 3.0.0-beta-1
* Add version info to user agent
* Setup pom for OSSRH deploy requirements

Prep needed for deployment

---

README.md
pom.xml

* Install instructions in README
* Remove duplicate maven plugin
* Enable and configure javadoc plugin

Installing instructions

---

pom.xml

* Bump okhttp3
* Make sure deps are properly scoped
Probably want to look at upgrading to okhttp version 4: https://square.github.io/okhttp/upgrading_to_okhttp_4/

Some pom fixes

---

openapi/api.yaml
src/main/java/com/recurly/v3/BaseClient.java
src/main/java/com/recurly/v3/Client.java
src/main/java/com/recurly/v3/FileSerializer.java
src/main/java/com/recurly/v3/QueryParams.java
src/main/java/com/recurly/v3/requests/ItemCreate.java
src/main/java/com/recurly/v3/requests/ItemUpdate.java
src/main/java/com/recurly/v3/requests/LineItemCreate.java
src/main/java/com/recurly/v3/requests/Pricing.java
src/main/java/com/recurly/v3/resources/BinaryFile.java
src/main/java/com/recurly/v3/resources/Item.java
src/main/java/com/recurly/v3/resources/LineItem.java
src/main/java/com/recurly/v3/resources/Pricing.java

- Adds capability to support `application/pdf` responses
- Adds `Item` support

Generated Updates for API version v2019-10-10

---

.bumpversion.cfg
README.md
pom.xml

* Adds PDF support https://github.com/recurly/recurly-client-java/pull/44
* Adds `Item` support https://github.com/recurly/recurly-client-java/pull/44
* Adds 3ds support https://github.com/recurly/recurly-client-java/pull/43

Release 3.1.0

---

pom.xml

Adding Doug to list of developers

---

src/main/java/com/recurly/v3/ApiException.java
src/main/java/com/recurly/v3/exception/BadRequestException.java
src/main/java/com/recurly/v3/exception/ExceptionFactory.java
src/main/java/com/recurly/v3/exception/ImmutableSubscriptionException.java
src/main/java/com/recurly/v3/exception/InternalServerException.java
src/main/java/com/recurly/v3/exception/InvalidApiKeyException.java
src/main/java/com/recurly/v3/exception/InvalidApiVersionException.java
src/main/java/com/recurly/v3/exception/InvalidContentTypeException.java
src/main/java/com/recurly/v3/exception/InvalidPermissionsException.java
src/main/java/com/recurly/v3/exception/InvalidTokenException.java
src/main/java/com/recurly/v3/exception/MissingFeatureException.java
src/main/java/com/recurly/v3/exception/NotFoundException.java
src/main/java/com/recurly/v3/exception/SimultaneousRequestException.java
src/main/java/com/recurly/v3/exception/TransactionException.java
src/main/java/com/recurly/v3/exception/UnauthorizedException.java
src/main/java/com/recurly/v3/exception/UnavailableInApiVersionException.java
src/main/java/com/recurly/v3/exception/UnknownApiVersionException.java
src/main/java/com/recurly/v3/exception/ValidationException.java
src/test/java/com/recurly/v3/BaseClientTest.java
src/test/resources/errors/transactionError.json
src/test/resources/errors/validationError.json

Resolves #58
Migration from Error to ErrorMayHaveTransaction

Resolves #58

---

.bumpversion.cfg
README.md
pom.xml

* Use ErrorMayHaveTransaction instead of Error #59 
* Include error params in exception message #56

Release 3.3.0

---

openapi/api.yaml
src/main/java/com/recurly/v3/Client.java
src/main/java/com/recurly/v3/requests/AddOnCreate.java
src/main/java/com/recurly/v3/requests/AddOnUpdate.java
src/main/java/com/recurly/v3/resources/AddOn.java
src/main/java/com/recurly/v3/resources/AddOnMini.java
src/main/java/com/recurly/v3/resources/ItemMini.java
src/main/java/com/recurly/v3/resources/PaymentMethod.java

* convert trial endpoint
* item-backed add-ons
* IBAN billing info

 Latest generated changes for v2019-10-10

---

.bumpversion.cfg
README.md
pom.xml

* Latest generated changes for v2019-10-10 #70
* convert trial endpoint
* item-backed add-ons
* IBAN billing info
* Latest v2019-10-10 Changes #62
* More documentation
* `Account#has_*` flag attributes
* Include `RateLimitedError`
* Gateway Token Support

Release 3.4.0

---

openapi/api.yaml
src/main/java/com/recurly/v3/requests/AddOnCreate.java
src/main/java/com/recurly/v3/requests/AddOnUpdate.java
src/main/java/com/recurly/v3/requests/SubscriptionAddOnCreate.java
src/main/java/com/recurly/v3/requests/SubscriptionAddOnTier.java
src/main/java/com/recurly/v3/requests/SubscriptionAddOnUpdate.java
src/main/java/com/recurly/v3/requests/Tier.java
src/main/java/com/recurly/v3/resources/AddOn.java
src/main/java/com/recurly/v3/resources/SubscriptionAddOn.java
src/main/java/com/recurly/v3/resources/SubscriptionAddOnTier.java
src/main/java/com/recurly/v3/resources/Tier.java

* Add `optional` to AddOnUpdate
* Adding quantity based pricing support

Tue Apr 14 20:23:36 UTC 2020 Upgrade API version v2019-10-10

---

src/main/java/com/recurly/v3/BaseClient.java
src/test/java/com/recurly/v3/BaseClientTest.java

Encoding path parameters

---

.bumpversion.cfg
README.md
pom.xml

[Full Changelog](https://github.com/recurly/recurly-client-java/compare/3.5.0...HEAD)
- Latest Features [\#93](https://github.com/recurly/recurly-client-java/pull/93) ([bhelx](https://github.com/bhelx))
- Updating error hierarchy and providing error handling for non-json error responses [\#92](https://github.com/recurly/recurly-client-java/pull/92) ([douglasmiller](https://github.com/douglasmiller))
- Fix interceptor stack overflow error [\#89](https://github.com/recurly/recurly-client-java/pull/89) ([NoahGreer](https://github.com/NoahGreer))
- Upgrade dependencies [\#91](https://github.com/recurly/recurly-client-java/pull/91) ([bhelx](https://github.com/bhelx))
- Refactoring tests to make use of shared code …

Release 3.6.0

---

README.md

Gives a general overview of the QueryParams object in the README.

Document QueryParams

---

openapi/api.yaml
src/main/java/com/recurly/v3/Client.java
src/main/java/com/recurly/v3/requests/SubscriptionAddOnCreate.java
src/main/java/com/recurly/v3/resources/SubscriptionAddOn.java
src/main/java/com/recurly/v3/resources/SubscriptionChangePreview.java

- Adds `preview_subscription_change` operation.
- Adds `addOnSource` attribute to `SubscriptionAddOnCreate` and `SubscriptionAddOn`.

Wed Jul  1 02:08:38 UTC 2020 Upgrade API version v2019-10-10

---

.bumpversion.cfg
README.md
pom.xml

[Full Changelog](https://github.com/recurly/recurly-client-java/compare/3.7.0...HEAD)
- Wed Jul  1 02:08:38 UTC 2020 Upgrade API version v2019-10-10 [\#100](https://github.com/recurly/recurly-client-java/pull/100) ([douglasmiller](https://github.com/douglasmiller))

Release 3.8.0

---

openapi/api.yaml
src/main/java/com/recurly/v3/requests/SubscriptionAddOnCreate.java
src/main/java/com/recurly/v3/requests/SubscriptionAddOnUpdate.java

- Adds `addOnSource` to `SubscriptionAddOnUpdate`

Mon Jul  6 14:50:29 UTC 2020 Upgrade API version v2019-10-10

---

.bumpversion.cfg
README.md
pom.xml

[Full Changelog](https://github.com/recurly/recurly-client-java/compare/3.8.0...HEAD)
- Mon Jul  6 14:50:29 UTC 2020 Upgrade API version v2019-10-10 [\#102](https://github.com/recurly/recurly-client-java/pull/102) ([douglasmiller](https://github.com/douglasmiller))

Release 3.9.0

---

.bumpversion.cfg
README.md
pom.xml

[Full Changelog](https://github.com/recurly/recurly-client-java/compare/3.9.0...HEAD)
- Latest Changes for 2019-10-10 \(usage, measured units, etc\) [\#104](https://github.com/recurly/recurly-client-java/pull/104) ([bhelx](https://github.com/bhelx))

Release 3.10.0

---

openapi/api.yaml
src/main/java/com/recurly/v3/requests/CouponCreate.java
src/main/java/com/recurly/v3/requests/SubscriptionChangeCreate.java
src/main/java/com/recurly/v3/resources/SubscriptionChange.java
src/main/java/com/recurly/v3/resources/SubscriptionChangePreview.java

- Adds Custom Fields to the Subscription Change and Subscription Change Preview endpoints.

Mon Aug 31 19:46:57 UTC 2020 Upgrade API version v2019-10-10

---

openapi/api.yaml
src/main/java/com/recurly/v3/Client.java
src/main/java/com/recurly/v3/QueryParams.java
src/main/java/com/recurly/v3/requests/AddOnCreate.java
src/main/java/com/recurly/v3/requests/LineItemCreate.java
src/main/java/com/recurly/v3/requests/SubscriptionAddOnCreate.java
src/main/java/com/recurly/v3/resources/Coupon.java
src/main/java/com/recurly/v3/resources/ExportDates.java
src/main/java/com/recurly/v3/resources/ExportFile.java
src/main/java/com/recurly/v3/resources/ExportFiles.java
src/main/java/com/recurly/v3/resources/UniqueCouponCode.java
src/main/java/com/recurly/v3/resources/Usage.java

* Adds `getExportDates` and `getExportFiles` operations for the [Automated Exports](https://developers.recurly.com/api/v2019-10-10/index.html#tag/automated_exports) feature.
* Adds `ExportDates`, `ExportFiles`, and `ExportFile` resources to support the `Automated Exports` feature.
* Adds `getBulkCouponCode` and `getBulkCouponId` methods to the `UniqueCouponCode` and `Coupon` resources.
* Adds `getUnitAmount` and `getUsagePercentage` methods to the `Usage` resource.
* Adds `setDate` query parameter to the `QueryParams` class.

Latest Changes for 2019-10-10 (Automated Exports, additional resource data attributes)

---

.bumpversion.cfg
README.md
pom.xml

[Full Changelog](https://github.com/recurly/recurly-client-java/compare/3.12.0...HEAD)
- Latest Changes for 2019-10-10 \(Automated Exports, additional resource data attributes\) [\#112](https://github.com/recurly/recurly-client-java/pull/112) ([douglasmiller](https://github.com/douglasmiller))

Release 3.13.0

---

openapi/api.yaml
src/main/java/com/recurly/v3/Client.java

* Adds `restoreCoupon` operation.

Mon Oct 19 20:39:41 UTC 2020 Upgrade API version v2019-10-10

---

.bumpversion.cfg
README.md
pom.xml

[Full Changelog](https://github.com/recurly/recurly-client-java/compare/3.14.0...HEAD)
- Latest Changes for 2019-10-10 \(Wallet, Item Coupons\) [\#117](https://github.com/recurly/recurly-client-java/pull/117) ([douglasmiller](https://github.com/douglasmiller))

Release 3.15.0

---

.bumpversion.cfg
README.md
pom.xml

[Full Changelog](https://github.com/recurly/recurly-client-java/compare/3.15.0...HEAD)
- Latest Changes for 2019-10-10 \(tax\_identifier / tax\_identifier\_type\) [\#121](https://github.com/recurly/recurly-client-java/pull/121) ([douglasmiller](https://github.com/douglasmiller))
- Latest Changes for 2019-10-10 [\#119](https://github.com/recurly/recurly-client-java/pull/119) ([douglasmiller](https://github.com/douglasmiller))

Release 3.16.0

---

.bumpversion.cfg
README.md
pom.xml

[Full Changelog](https://github.com/recurly/recurly-client-java/compare/3.16.0...HEAD)
- Latest Changes for 2019-10-10 [\#123](https://github.com/recurly/recurly-client-java/pull/123) ([douglasmiller](https://github.com/douglasmiller))

Release 3.17.0

---

scripts/clean
src/main/java/com/recurly/v3/Constants.java
src/main/java/com/recurly/v3/exception/ExceptionFactory.java

Small tweaks in the `ExceptionFactory` and addition of the `Constants` class which will be used in 4.x clients

Small tweaks

---

openapi/api.yaml
src/main/java/com/recurly/v3/Client.java
src/main/java/com/recurly/v3/Constants.java
src/main/java/com/recurly/v3/exception/ExceptionFactory.java
src/main/java/com/recurly/v3/requests/CouponRedemptionCreate.java
src/main/java/com/recurly/v3/resources/CouponRedemption.java

* Adds `GetSubscriptionId` and `SetSubscriptionId` methods to the `CouponRedemption` resource and the `CouponRedemptionCreate` request.

Latest Changes for 2019-10-10

---

src/test/java/com/recurly/v3/BaseClientTest.java

Some updates added to the 3.x client were missed when creating the 4.x client.

Sync updates not ported from 3.x client

---

.bumpversion.cfg
README.md
pom.xml

[Full Changelog](https://github.com/recurly/recurly-client-java/compare/4.0.0...HEAD)
- Generated Latest Changes for v2021-02-25 [\#139](https://github.com/recurly/recurly-client-java/pull/139) ([recurly-integrations](https://github.com/recurly-integrations))
- Sync updates not ported from 3.x client [\#136](https://github.com/recurly/recurly-client-java/pull/136) ([douglasmiller](https://github.com/douglasmiller))

Release 4.0.1
