- pom.xml
- src/main/java/com/recurly/v3/QueryParams.java
- src/test/java/com/recurly/v3/JsonSerializerTest.java
- src/test/java/com/recurly/v3/QueryParamsTest.java
Adds a couple of tests around the query params. `setLimit` is the only portion that's truly generated (everything else that I'm testing here is written directly into the generator template). The rest of the dynamic methods do not have tests around them, but there's no way to exclude them from coverage unless we exclude the entire class (which may be the best option, but I haven't done that just yet).
> Add test for query params

- scripts/format
Using git ls-files doesn't work in situations where files have been
removed and not comited. Instead of trying to get it to work with
ls-files, it's much simpler and more robust to use a normal `ls` and format every
file.
> Fix format script

- pom.xml
The transitive deps for xercesImpl and plexus-utils were out of date and therefore flagged by Snyk. This updates them to non-vulnerable versions. Unit tests pass locally and jacoco still successfully creates the report when you increment the `forkCount` to 1.
> Specify transitive dependency versions

- README.md
- scripts/build
- scripts/format
- scripts/test
- src/main/java/com/recurly/v3/BaseClient.java
- src/main/java/com/recurly/v3/Client.java
- src/test/java/com/recurly/v3/BaseClientTest.java
- src/test/java/com/recurly/v3/ClientTest.java
- src/test/java/com/recurly/v3/PagerTest.java
- src/test/java/com/recurly/v3/fixtures/MockClient.java
This removes the constraint of required site-id to initialize a client.
The site can be inferred from the api key. We will be adding ways to
use multiple sites with the same client in the future. This sets us
up so we can do that in a non-breaking way.
> Remove the site-id constraint from Client

- src/main/java/com/recurly/v3/BaseClient.java
URLs were being built with double forward slashes: `https://v3.recurly.com//desired/path`
> Fixing double forward slash in generated URLs

- .bumpversion.cfg
- README.md
- pom.xml
- src/main/java/com/recurly/v3/QueryParams.java
Fixes an issue with requesting a list of resources with specific `ids`. The server expects a CSV string of ids, but the api spec specifies that the `ids` should be specified as an array. 
This fix maintains developer happiness by maintaining the ability to specify an array of ids that are transformed to a CSV string when the request is sent to the server.
Resolves https://github.com/recurly/recurly-client-java/issues/47
> Convert Array params to CSV strings

- src/main/java/com/recurly/v3/JsonSerializer.java
Updating the JsonSerializer to return empty string instead of "null" when attempting to serialize a null body.
Fixes the error:
```
Failed validation: Please remove the following unpermitted parameters from your request: _json.
```
> Fixing invalid request body (unpermitted parameters _json)

- src/main/java/com/recurly/v3/ApiException.java
Resolves #55
This may be redundant for some errors, but provides a better default when you don't explicitly catch exceptions and render their error params.
Example stack trace:
```
Caused by: com.recurly.v3.exception.ValidationException: Purchase could not be completed. [{param=account.billing_info.first_name, message=can't be blank}, {param=account.billing_info.last_name, message=can't be blank}, {param=account.billing_info.number, message=is required}, {param=account.billing_info.country, message=can't be empty}, {param=account.code, message=can't be blank}, {param=account.code, message=is invalid}]
at com.recurly.v3.exception.ExceptionFactory.getExceptionClass(ExceptionFactory.java:61)
at com.recurly.v3.JsonSerializer.deserializeError(JsonSerializer.java:32)
at …
```
> Include error params in exception message

- openapi/api.yaml
- src/main/java/com/recurly/v3/exception/ExceptionFactory.java
- src/main/java/com/recurly/v3/exception/RateLimitedException.java
- src/main/java/com/recurly/v3/requests/AccountAcquisitionUpdatable.java
- src/main/java/com/recurly/v3/requests/AccountCreate.java
- src/main/java/com/recurly/v3/requests/AccountPurchase.java
- src/main/java/com/recurly/v3/requests/AccountUpdate.java
- src/main/java/com/recurly/v3/requests/BillingInfoCreate.java
- src/main/java/com/recurly/v3/requests/ItemCreate.java
- src/main/java/com/recurly/v3/requests/ItemUpdate.java
- src/main/java/com/recurly/v3/requests/SubscriptionChangeCreate.java
- src/main/java/com/recurly/v3/requests/SubscriptionCreate.java
- src/main/java/com/recurly/v3/requests/SubscriptionPurchase.java
- src/main/java/com/recurly/v3/requests/SubscriptionUpdate.java
- src/main/java/com/recurly/v3/resources/Account.java
- src/main/java/com/recurly/v3/resources/AccountAcquisition.java
- src/main/java/com/recurly/v3/resources/AccountBalance.java
- src/main/java/com/recurly/v3/resources/Coupon.java
- src/main/java/com/recurly/v3/resources/CouponMini.java
- src/main/java/com/recurly/v3/resources/CreditPayment.java
- src/main/java/com/recurly/v3/resources/Invoice.java
- src/main/java/com/recurly/v3/resources/Item.java
- src/main/java/com/recurly/v3/resources/LineItem.java
- src/main/java/com/recurly/v3/resources/PaymentMethod.java
- src/main/java/com/recurly/v3/resources/Subscription.java
- src/main/java/com/recurly/v3/resources/SubscriptionAddOn.java
- src/main/java/com/recurly/v3/resources/SubscriptionChange.java
- src/main/java/com/recurly/v3/resources/Transaction.java
* More documentation
* `Account#has_*` flag attributes
* Include `RateLimitedError`
* Gateway Token Support
> Latest v2019-10-10 Changes

- .github_changelog_generator
- scripts/release
The internal use release script incorrectly was echoing the commands to build and deploy instead of running them.
> Fixing release script

- .bumpversion.cfg
- README.md
- pom.xml
[Full Changelog](https://github.com/recurly/recurly-client-java/compare/3.4.0...HEAD)
- How to refund invoice when amount has cents ? [\#73](https://github.com/recurly/recurly-client-java/issues/73)
- Fixing release script [\#78](https://github.com/recurly/recurly-client-java/pull/78) ([douglasmiller](https://github.com/douglasmiller))
- Fri Mar 20 17:42:07 UTC 2020 Upgrade API version v2019-10-10 [\#77](https://github.com/recurly/recurly-client-java/pull/77) ([douglasmiller](https://github.com/douglasmiller))
- Adding changelog generation [\#74](https://github.com/recurly/recurly-client-java/pull/74) ([douglasmiller](https://github.com/douglasmiller))
-  Add request for stack trace in issue report …
> Release 3.4.1

- README.md
- src/main/java/com/recurly/v3/BaseClient.java
- src/main/java/com/recurly/v3/Pager.java
- src/test/java/com/recurly/v3/PagerTest.java
Adds the `getFirst` and `getCount` methods to the `Pager` class.
The `getFirst` method will perform a request to the API with the `limit` set to 1 and will only return the first result from the server.
The `getCount` method will perform a `HEAD` request to the API for the appropriate endpoint. The value of the response header, `recurly-total-records`, will be returned. This is the total number of records that will be returned by the pager.
> Adding #getFirst and #getCount methods to Pager

- .bumpversion.cfg
- README.md
- pom.xml
[Full Changelog](https://github.com/recurly/recurly-client-java/compare/3.4.1...HEAD)
- Tue Apr 14 20:23:36 UTC 2020 Upgrade API version v2019-10-10 [\#84](https://github.com/recurly/recurly-client-java/pull/84) ([bhelx](https://github.com/bhelx))
- Adding \#getFirst and \#getCount methods to Pager [\#82](https://github.com/recurly/recurly-client-java/pull/82) ([douglasmiller](https://github.com/douglasmiller))
- Included the to-be released changes in the changelog [\#83](https://github.com/recurly/recurly-client-java/pull/83) ([douglasmiller](https://github.com/douglasmiller))
- Updating release script to be uniform across all clients [\#81](https://github.com/recurly/recurly-client-java/pull/81) …
> Release 3.5.0

- src/test/java/com/recurly/v3/HeaderInterceptorTest.java
This test regex was too strict. Some systems only give major number. Example (`java 14`).
> Loosening the restrictions on generated user agent string

- src/main/java/com/recurly/v3/BaseClient.java
- src/test/java/com/recurly/v3/BaseClientTest.java
Adding a validation method that will ensure that path parameters are not empty strings to address issues where a `get_*` operation (`/resources/{resource_id}`) does not get handled by the API as a `list_*` operations (`/resources/`).
> Ensure that path parameters are not empty strings

- src/test/java/com/recurly/v3/BaseClientTest.java
- src/test/java/com/recurly/v3/PagerTest.java
- src/test/java/com/recurly/v3/fixtures/MockClient.java
Refactoring the `Pager` and `BaseClient` tests to make use of shared code to mock the `OkHttpClient`
> Refactoring tests to make use of shared code

- src/main/java/com/recurly/v3/BaseClient.java
**The bug:**
After creating enough new Client objects, the header interceptor chain grows so large that it causes a `java.lang.StackOverflowError` error the next time a Client tries to make a request.
This means that in a long-lived web application, using this library creates a ticking time bomb that will eventually cause it to break.
**Stack trace:**
```
java.lang.StackOverflowError
at okhttp3.Headers.newBuilder(Headers.java:144)
at okhttp3.Request$Builder.<init>(Request.java:140)
at okhttp3.Request.newBuilder(Request.java:93)
at com.recurly.v3.http.HeaderInterceptor.intercept(HeaderInterceptor.java:26)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at …
```
> Fix interceptor stack overflow error

- .bumpversion.cfg
- README.md
- pom.xml
[Full Changelog](https://github.com/recurly/recurly-client-java/compare/3.6.0...HEAD)
- Mon Jun 29 17:11:45 UTC 2020 Upgrade API version v2019-10-10 [\#98](https://github.com/recurly/recurly-client-java/pull/98) ([douglasmiller](https://github.com/douglasmiller))
- Bump Dependencies [\#97](https://github.com/recurly/recurly-client-java/pull/97) ([bhelx](https://github.com/bhelx))
- This library does not work with Play Framework [\#96](https://github.com/recurly/recurly-client-java/issues/96)
- Document QueryParams [\#95](https://github.com/recurly/recurly-client-java/pull/95) ([bhelx](https://github.com/bhelx))
> Release 3.7.0

- openapi/api.yaml
- src/main/java/com/recurly/v3/Client.java
- src/main/java/com/recurly/v3/QueryParams.java
- src/main/java/com/recurly/v3/exception/ExceptionFactory.java
- src/main/java/com/recurly/v3/exception/TimeoutException.java
- src/main/java/com/recurly/v3/requests/AddOnCreate.java
- src/main/java/com/recurly/v3/requests/AddOnUpdate.java
- src/main/java/com/recurly/v3/requests/MeasuredUnitCreate.java
- src/main/java/com/recurly/v3/requests/MeasuredUnitUpdate.java
- src/main/java/com/recurly/v3/requests/SubscriptionAddOnCreate.java
- src/main/java/com/recurly/v3/requests/SubscriptionAddOnUpdate.java
- src/main/java/com/recurly/v3/requests/SubscriptionPurchase.java
- src/main/java/com/recurly/v3/requests/UsageCreate.java
- src/main/java/com/recurly/v3/resources/AddOn.java
- src/main/java/com/recurly/v3/resources/AddOnMini.java
- src/main/java/com/recurly/v3/resources/MeasuredUnit.java
- src/main/java/com/recurly/v3/resources/SubscriptionAddOn.java
- src/main/java/com/recurly/v3/resources/SubscriptionChange.java
- src/main/java/com/recurly/v3/resources/SubscriptionChangePreview.java
- src/main/java/com/recurly/v3/resources/Usage.java
* Usage and measured units support
* Added `invoiceCollection` to response for `createSubscriptionChange`
* Support `addOnType` on addons
> Latest Changes for 2019-10-10 (usage, measured units, etc)

- .bumpversion.cfg
- README.md
- pom.xml
[Full Changelog](https://github.com/recurly/recurly-client-java/compare/3.11.0...HEAD)
- Mon Aug 31 19:46:57 UTC 2020 Upgrade API version v2019-10-10 [\#109](https://github.com/recurly/recurly-client-java/pull/109) ([douglasmiller](https://github.com/douglasmiller))
- Code of Conduct [\#108](https://github.com/recurly/recurly-client-java/pull/108) ([bhelx](https://github.com/bhelx))
> Release 3.12.0

- .bumpversion.cfg
- README.md
- pom.xml
[Full Changelog](https://github.com/recurly/recurly-client-java/compare/3.13.0...HEAD)
- Mon Oct 19 20:39:41 UTC 2020 Upgrade API version v2019-10-10 [\#114](https://github.com/recurly/recurly-client-java/pull/114) ([douglasmiller](https://github.com/douglasmiller))
> Release 3.14.0

- openapi/api.yaml
- src/main/java/com/recurly/v3/QueryParams.java
- src/main/java/com/recurly/v3/resources/Subscription.java
- Adds the `state` parameter to the `listAccountCouponRedemptions` operation.
- Adds the `charge` parameter to the `terminateSubscription` operation so that a merchant can choose to not bill a customer for un-billed usage when terminating a subscription
> Latest Changes for 2019-10-10

- src/main/java/com/recurly/v3/BaseClient.java
- src/test/java/com/recurly/v3/BaseClientTest.java
Fixing an issue with the pattern matching for path interpolation. This issue only impacts the Automated Exports endpoints currently.
> Interpolate path pattern has capture parens in wrong place

- src/test/java/com/recurly/v3/BaseClientTest.java
Add a test case to verify that unknown error types are thrown as a generic ApiException
See https://github.com/recurly/recurly-client-python/pull/372, https://github.com/recurly/recurly-client-ruby/pull/641 and https://github.com/recurly/recurly-client-dotnet/pull/587 for reference.
> Test for fallback to generic api error

- .bumpversion.cfg
- README.md
- pom.xml
[Full Changelog](https://github.com/recurly/recurly-client-java/compare/3.17.0...HEAD)
- Latest Changes for 2019-10-10 [\#128](https://github.com/recurly/recurly-client-java/pull/128) ([douglasmiller](https://github.com/douglasmiller))
- Interpolate path pattern has capture parens in wrong place [\#125](https://github.com/recurly/recurly-client-java/pull/125) ([douglasmiller](https://github.com/douglasmiller))
- Small tweaks in the ExceptionFactory and preparation for next major version [\#126](https://github.com/recurly/recurly-client-java/pull/126) ([douglasmiller](https://github.com/douglasmiller))
- Test for fallback to generic api error [\#120](https://github.com/recurly/recurly-client-java/pull/120) …
> Release 3.18.0

- src/main/java/com/recurly/v3/BaseClient.java
- src/test/java/com/recurly/v3/BaseClientTest.java
- src/test/java/com/recurly/v3/fixtures/MockQueryParams.java
An extension of https://github.com/recurly/recurly-client-java/pull/127 which added `Enum` support. Query string parameters were not properly using the `SerializedName` annotation when generating the request.
> Convert query string enums to their SerializedName

- .bumpversion.cfg
- README.md
- pom.xml
- src/test/java/com/recurly/v3/HeaderInterceptorTest.java
[Full Changelog](https://github.com/recurly/recurly-client-java/compare/3.18.0...HEAD)
The 4.x major version of the client pairs with the `v2021-02-25` API version. This version of the client and the API contain breaking changes that should be considered before upgrading your integration.
All changes to the core API are documented in the [Developer Portal changelog](https://developers.recurly.com/api/changelog.html#v2021-02-25---current-ga-version)
- Add enum support where they are defined in the OpenApi specification. [[#127](https://github.com/recurly/recurly-client-java/pull/127)]
- Convert `Float` to `BigDecimal`. [#133]
- Interpolate path pattern has capture parens in wrong place [\#125](https://github.com/recurly/recurly-client-java/pull/125) …
> Release 4.0.0
